#  ______ ____  _   _                       #
# |  ____|___ \| \ | |                      #
# | |__    __) |  \| | __ _ _ __ ___   ___  #
# |  __|  |__ <| . ` |/ _` | '_ ` _ \ / _ \ #
# | |     ___) | |\  | (_| | | | | | |  __/ #
# |_|    |____/|_| \_|\__,_|_| |_| |_|\___| #
#                                           #

#If you don't want to change server brand in debug menu
#on specific server - add server name below
excluded-servers:
  - "excluded"
#Groups edit
groups:
  #Default group for everyone, must present in config
  everyone:
    f3names:
      - "&6This is a BungeeCord version of &3F3Name"
      - "&6Everything the same as in the Bukkit version"
      - "&6Except excluded-servers list above and built-in placeholders"
      - "&6Your ping: &2%player_ping%&6, current server name &2%server_name%"
      - "&6It sends to all servers on your network"
    shuffle: false
    #Update time in ticks
    update-time: 100
  #Example group, change name to your
  "example":
    f3names:
      - "&6This is an example group"
      - "&6This text will show to players with &cexample &6group"
      - "&6Player groups sorted by their weight"
    #Shuffle and update-time is optional, their default value are showed above

#Prevents messages above from sending. Enable this if you have server with plugin
#on network, but don't want to change server brand on others server in network
only-api: false

#Use colored console. Disable it if you don't see colors
coloredConsole: true
