#  ______ ____  _   _                       #
# |  ____|___ \| \ | |                      #
# | |__    __) |  \| | __ _ _ __ ___   ___  #
# |  __|  |__ <| . ` |/ _` | '_ ` _ \ / _ \ #
# | |     ___) | |\  | (_| | | | | | |  __/ #
# |_|    |____/|_| \_|\__,_|_| |_| |_|\___| #
#                                           #

#Groups edit
groups:
  #Default group for everyone, must present in config
  everyone:
    f3names:
      - "&6This is an example configuration file"
      - "&6Use this list to set multiple names in debug screen"
      - "&6It also have support of PlaceholderAPI,&r %player_displayname%"
      - "&6Your ping: &2%player_ping%&6, current world time &2%player_world_time_24%"
    #Choose random string from this list on update
    shuffle: false
    #Update time for list in ticks (1 second = 20 ticks)
    update-time: 200
  #Example group, change name to your
  "example":
    f3names:
      - "&6This is an example group"
      - "&6This text will show to players with &cexample &6group"
      - "&6Player groups sorted by their weight"
    #Shuffle and update-time is optional, their default value are showed above

#If set to true, disables this plugin and gives a bungeecord plugin ability to send
#messages using this plugin. It allows bungee to use hooked plugins on the server
bungeecord-as-primary: false

#Use colored console. Disable it if you don't see colors
coloredConsole: true

#Auto update for plugin
auto-update: true