#  ______ ____  _   _                       #
# |  ____|___ \| \ | |                      #
# | |__    __) |  \| | __ _ _ __ ___   ___  #
# |  __|  |__ <| . ` |/ _` | '_ ` _ \ / _ \ #
# | |     ___) | |\  | (_| | | | | | |  __/ #
# |_|    |____/|_| \_|\__,_|_| |_| |_|\___| #
#                                           #

groups:
  #Default group. DO NOT REMOVE!
  everyone:
    f3names:
      #Max 256 characters per line
      - "&6This is an example configuration file"
      - "&6Use this list to set multiple names in debug screen"
      - "&6It also have support of PlaceholderAPI,&r %player_displayname%"
      - "&6Your ping: &2%player_ping%&6, current world time &2%player_world_time_24%"
    #Shuffle that list before displaying?
    shuffle: false
    #Refresh rate in ticks (1 second = 20 ticks)
    update-time: 200
  #Some example. You can edit or remove this
  "example":
    f3names:
      - "&6This is an example group"
      - "&6This text will show to players with &cexample &6group"
      - "&6Player groups sorted by their weight"
    #Shuffle and update-time are optional, their default values shown above

#If set to true, disables this plugin and gives bungeecord side plugin ability to send
#messages through this plugin. It allows bungee to use hooked plugins (PlaceholderAPI, Vault, LuckPerms)
bungeecord-as-primary: false

#Use colored console. Disable this if your console doesn't have support for colors
coloredConsole: true

#Auto update for the plugin
auto-update: true